# This is a basic workflow to help you get started with Actions

name: CI-nrf

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - "nrf52"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: static analysis
        working-directory: nrf52/hello_world
        run: cppcheck src/main.c

      # Runs a set of commands using the runners shell
      - name: build 
        working-directory: nrf52/hello_world
        run: west build -p -b nrf52dk_nrf52832 --build-dir build
        
  upload:
    runs-on: self-hosted
    needs:
      compile
    steps:
      - name: flash elf
        working-directory: nrf52/hello_world
        run: west flash --build-dir build

  logging:
    runs-on: self-hosted
    needs:
      compile
    steps:
      - name: start monitor
        run: |
          screen -L /dev/tty.usbmodem0006820286461 115200

      - name: delay
        run: sleep 10

      - name: stop_monitor
        run: |
          screen_ID="$(screen -ls | grep ttys | cut -c 2-5)"
          screen -SX $screen_ID quit

  verify:
    runs-on: self-hosted
    needs:
      compile
    steps:
      - name: verify log
        run: cat screenlog.0